version: 2
jobs:
  build:
    docker:
      - image: diehlpk/parallelbook
    steps:
      - checkout
      - run: module load openmpi
      - run: mkdir build
      - run: cmake -DWITH_PAR_ALG=ON -DWITH_HPX=ON -S . -B build
      - run: cd build && make -j 2
      - run: cd build && ctest
      - run: rm -rf build
      - run: export CXX=clang++ && cmake -DWITH_PAR_ALG=OFF -DWITH_HPX=OFF -S . -B build
      - run: cd build && make -j 2
      - run: cd build && ctest
      - run: rm -rf build
