version: 2
jobs:
  build:
    docker:
      - image: stevenrbrandt/cxxex-src
    steps:
      - checkout
      - run: mkdir build
      - run: export PATH=$PATH:/usr/lib64/openmpi/bin/ && cmake -S . -B build
      - run: cd build && make -j 2
      #- run: cd build && ctest
      - run: rm -rf build
      #- run: export CXX=clang++ && cmake -S . -B build
      #- run: cd build && make -j 2
      #- run: cd build && ctest
      #- run: rm -rf build
      
