version: 2
jobs:
  build:
    docker:
      - image: diehlpk/parallelbook
    steps:
      - checkout
      - run: mkdir build
      - run: cmake -S . -B build
      - run: cd build && make -j 2
      - run: rm -rf build
      - run: export CXX=clang++ && cmake -S . -B build
      - run: cd build && make -j 2
