version: 2
jobs:
  build:
    docker:
      - image: diehlpk/parallelbook
    steps:
      - checkout
      - run: source /etc/profile.d/modules.sh
      - run: module load mpi/openmpi-x86_64
      - run: mkdir build
      - run: cmake -DWITH_PAR_ALG=ON -DWITH_HPX=ON -S . -B build
      - run: cd build && make -j 2
      - run: cd build && ctest
      - run: rm -rf build
      - run: export CXX=clang++ && cmake -DWITH_PAR_ALG=OFF -DWITH_HPX=OFF -S . -B build
      - run: cd build && make -j 2
      - run: cd build && ctest
      - run: rm -rf build
